CREATE OR REPLACE VIEW DB_PUBBLICA
(PR_COD_PRAT,OGGETTO,PRATICA,ID_TIPO,DESC_TIPO,ID_UFF,DESC_UFF,ATTO,TIPO_ATTO,DATA_ATTO,DOC,DATA_DOC,PERCORSO)
AS
SELECT A.PR_COD_PRAT,A.PR_PRAT_DESC AS OGGETTO,A.PR_PRAT_NUM1||'-'||A.PR_PRAT_NUM2||'-'||A.PR_PRAT_NUM3 AS PRATICA,A.PR_PRAT_TIPO,B.M1_TAB_DES AS DESC_TIPO,B.GI_COD_ELEUFF AS ID_UFF,C.M1_TAB_DES AS DESC_UFF,D.GI_NUM_PROVV1||'-'||D.GI_NUM_PROVV2||'-'||D.GI_NUM_PROVV3 AS ATTO,D.GI_TIP_PROVV AS TIPO_ATTO,D.GI_DAT_INI AS DATA_ATTO,E.GI_PRT_DES AS DOC,E.GI_PRT_DAT AS DATA_DOC,F.DK_DOC_PERCORSO||'\'||F.DK_DOC_UID AS PERCORSO FROM M1_TABPR_PRAT A,GI_TAB_DEFPRA B,M1_TAB_UFF C,GI_TAB_PROVV D,GI_TAB_PRASTM E,DK_DOC F,GI_TAB_PRAITE G
WHERE A.PR_PRAT_TIPO=B.M1_TAB_COD
AND B.GI_COD_ELEUFF=C.M1_TAB_COD
AND A.PR_COD_PRAT=D.PR_COD_PRAT
AND A.PR_COD_PRAT=E.PR_COD_PRAT
AND E.GI_PRT_FILE=F.DK_DOC_UID
AND A.PR_COD_PRAT=G.PR_COD_PRAT
AND E.GI_COD_ELESUC=G.GI_COD_ELESUC
AND G.GI_COD_ELECOD=2109
AND G.GI_DAT_FIN IS NOT NULL;